/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.apresentacao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import tcc.dominio.FormaPagamento;
import tcc.dominio.ContasAPagar;
import tcc.negocio.ClienteFisicoController;
import tcc.negocio.ContasAPagarController;


/**
 *
 * @author Breno-
 */
public class CadastroContaAPagar extends javax.swing.JInternalFrame {

    ClienteFisicoController Cliente_fisicoController = new ClienteFisicoController();
    ContasAPagarController Pagar_contasController = new ContasAPagarController();
   
    Locale locale = new Locale("pt","BR");
    GregorianCalendar calendar = new GregorianCalendar();
    SimpleDateFormat formatador2 = new SimpleDateFormat("dd/MM/yyyy");

    public CadastroContaAPagar() {
        initComponents();
        situacao.setText("EM ABERTO");
        situacao.setEnabled(false);
        carregarFormasdepagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        data_vencimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        FormaPagamento = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        contaBancaria = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        situacao = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setClosable(true);
        setTitle("Lorem Auctor - Cadastrar Contas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Empresa:");

        empresa.setBackground(new java.awt.Color(255, 255, 204));
        empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empresaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valor:");

        valor.setBackground(new java.awt.Color(255, 255, 204));
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data de Vencimento:");

        data_vencimento.setBackground(new java.awt.Color(255, 255, 204));
        try {
            data_vencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_vencimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_vencimento.setText("  /     /    ");
        data_vencimento.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Forma de Pagamento:");

        FormaPagamento.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Conta:");

        contaBancaria.setBackground(new java.awt.Color(255, 255, 204));
        contaBancaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contaBancariaKeyReleased(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel.setText("Situação:");

        situacao.setBackground(new java.awt.Color(255, 255, 204));

        salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salvar.setForeground(new java.awt.Color(0, 0, 102));
        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/13.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(valor)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(68, 68, 68)
                                .addComponent(data_vencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contaBancaria, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(situacao)
                                    .addComponent(salvar, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(contaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel)
                    .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salvar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyReleased
                 if((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46))
        if(evt.getKeyCode() < 96 || evt.getKeyCode() > 105)
        if(valor.getText().length() > 0)
            valor.setText(valor.getText().
            substring(0, valor.getText().length()-1));
        if(evt.getKeyCode() == 44 || evt.getKeyCode() == 110)
            valor.setText(valor.getText()+".");
    }//GEN-LAST:event_valorKeyReleased

    private void empresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empresaKeyReleased
        
        empresa.setText(empresa.getText().toUpperCase());
    }//GEN-LAST:event_empresaKeyReleased

    private void contaBancariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contaBancariaKeyReleased
        
        contaBancaria.setText(contaBancaria.getText().toUpperCase());
    }//GEN-LAST:event_contaBancariaKeyReleased

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed

if(empresa.getText().equals("")) {
      JOptionPane.showMessageDialog(null, "Preencha o nome da Empresa", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
}
if(valor.getText().equals("")) {
      JOptionPane.showMessageDialog(null, "Preencha o valor da Conta", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
}
if(FormaPagamento == null) {
      JOptionPane.showMessageDialog(null, "Preencha a Forma de Pagamento", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
}

if(data_vencimento.getText().length() < 9) {
      JOptionPane.showMessageDialog(null, "Preencha a Data de Vencimento", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
}
if(contaBancaria.getText().equals("")) {
      JOptionPane.showMessageDialog(null, "Preencha o nome de alguém com uma conta bancaria válida. Se não for necessário, preencha c/ qualq. tecla", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
}
        
         ContasAPagar pc = new ContasAPagar();
        
        FormaPagamento forma_pagamento =  (FormaPagamento) FormaPagamento.getSelectedItem();
        BigDecimal valor1  = new BigDecimal(valor.getText().trim());
        
        
        
        pc.setEmpresa(empresa.getText().trim());
        pc.setFormaPagamento(forma_pagamento);
        pc.setValor(valor1);
        pc.setDataVencimento(data_vencimento.getText());
        pc.setContabancaria(contaBancaria.getText());
        pc.setSituacaoConta(situacao.getText());
       
        try {
            Pagar_contasController.CadastrarContas(pc);
            JOptionPane.showMessageDialog(null, "Conta cadastrada com sucesso!");
            limparDados();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar o cadastro da conta!");
        }
        
    }//GEN-LAST:event_salvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FormaPagamento;
    private javax.swing.JTextField contaBancaria;
    private javax.swing.JFormattedTextField data_vencimento;
    private javax.swing.JTextField empresa;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField situacao;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables

private void carregarFormasdepagamento() {
       try {
           List<FormaPagamento> pagamentos = Pagar_contasController.listarFormaspagamento();
           for (FormaPagamento pagamento : pagamentos) {
               
               FormaPagamento.addItem(pagamento);
           }
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Não foi possivel mostrar as formas de pagamento!");
           ex.printStackTrace();
       }
    }

    private void limparDados() {
        valor.setText("");
        empresa.setText("");
       
    }

}
