/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.apresentacao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import tcc.dominio.Produtos;
import tcc.dominio.TipoProduto;
import tcc.negocio.ProdutosController;

public class Cadastrodepeças extends javax.swing.JInternalFrame {

    ProdutosController ProdutosController = new ProdutosController();

    public Cadastrodepeças() {
        initComponents();
        carregarTabela();

        salvar.setHorizontalTextPosition(SwingConstants.RIGHT);
        margemLucroRevenda.setEnabled(false);
        margemLucroVarejo.setEnabled(false);
        nomeProdutoPecas.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        nomeProdutoPecas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        valorVarejoPecas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        localizacaoProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        valorCompraPecas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        valorRevendaPecas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        descricaoPecas = new javax.swing.JComboBox();
        salvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        unidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qtdEstoque = new javax.swing.JTextField();
        painelEstipulador = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        margemLucroRevenda = new javax.swing.JTextField();
        margemLucroVarejo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botaoRevenda = new javax.swing.JRadioButton();
        botaoVarejo = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Lorem Auctor - Cadastro de Produtos");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(601, 314));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nomeProdutoPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomeProdutoPecas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nomeProdutoPecas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeProdutoPecasKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nome do Produto:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Valor de Varejo:");

        valorVarejoPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorVarejoPecas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valorVarejoPecas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorVarejoPecasKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Localização:");

        localizacaoProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        localizacaoProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        localizacaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizacaoProdutoActionPerformed(evt);
            }
        });
        localizacaoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                localizacaoProdutoKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Valor de Compra:");

        valorCompraPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorCompraPecas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valorCompraPecas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorCompraPecasFocusLost(evt);
            }
        });
        valorCompraPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCompraPecasActionPerformed(evt);
            }
        });
        valorCompraPecas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorCompraPecasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorCompraPecasKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Valor de Revenda:");

        valorRevendaPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorRevendaPecas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valorRevendaPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorRevendaPecasActionPerformed(evt);
            }
        });
        valorRevendaPecas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorRevendaPecasKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Marca:");

        marca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        marca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marcaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Descrição:");

        descricaoPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoPecasActionPerformed(evt);
            }
        });

        salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salvar.setForeground(new java.awt.Color(0, 0, 102));
        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/13.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.setAlignmentX(0.5F);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Unidade:");

        unidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        unidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadeKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade no Estoque:");

        qtdEstoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtdEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        qtdEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtdEstoqueKeyReleased(evt);
            }
        });

        painelEstipulador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Margem de lucro para revenda:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Margem de lucro para varejo:");

        margemLucroRevenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                margemLucroRevendaKeyReleased(evt);
            }
        });

        margemLucroVarejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                margemLucroVarejoKeyReleased(evt);
            }
        });

        jLabel7.setText("%");

        jLabel8.setText("%");

        botaoRevenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRevendaActionPerformed(evt);
            }
        });

        botaoVarejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVarejoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEstipuladorLayout = new javax.swing.GroupLayout(painelEstipulador);
        painelEstipulador.setLayout(painelEstipuladorLayout);
        painelEstipuladorLayout.setHorizontalGroup(
            painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstipuladorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(margemLucroRevenda, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(margemLucroVarejo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEstipuladorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRevenda))
                    .addGroup(painelEstipuladorLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoVarejo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEstipuladorLayout.setVerticalGroup(
            painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstipuladorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRevenda)
                    .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(margemLucroRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(19, 19, 19)
                .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEstipuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(margemLucroVarejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(botaoVarejo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelEstipulador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel13)
                                        .addComponent(valorVarejoPecas)
                                        .addComponent(nomeProdutoPecas)
                                        .addComponent(localizacaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel2)
                                        .addComponent(marca)
                                        .addComponent(valorCompraPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel12)
                                        .addComponent(valorRevendaPecas)
                                        .addComponent(descricaoPecas, 0, 160, Short.MAX_VALUE))
                                    .addComponent(qtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeProdutoPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorRevendaPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(valorVarejoPecas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoPecas, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorCompraPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marca)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(localizacaoProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(unidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelEstipulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salvar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 681, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void localizacaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizacaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localizacaoProdutoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed

        if (nomeProdutoPecas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o nome do Produto", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (valorCompraPecas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o valor de Compra do Produto", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (valorRevendaPecas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o valor de Revenda", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (valorVarejoPecas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o valor de Varejo do Produto", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (marca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha a Marca", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (descricaoPecas.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha a Descrição da peça", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (localizacaoProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha a Localização do Produto", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (qtdEstoque.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha a quantidade de estoque do Produto", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Produtos produto = new Produtos();

        BigDecimal campoValorRevenda = new BigDecimal((valorRevendaPecas.getText().trim()));
        BigDecimal campoValorVarejo = new BigDecimal((valorVarejoPecas.getText().trim()));
        BigDecimal campoValorCompra = new BigDecimal((valorCompraPecas.getText().trim()));
        int quantidadeEstoque = Integer.parseInt(qtdEstoque.getText().trim());
        TipoProduto tipoproduto = (TipoProduto) descricaoPecas.getSelectedItem();

        produto.setNomeProduto(nomeProdutoPecas.getText().trim());
        produto.setPrecoVarejo(campoValorVarejo);
        produto.setPrecoRevenda(campoValorRevenda);
        produto.setPrecoDeCompra(campoValorCompra);
        produto.setDescricao(tipoproduto);
        produto.setLocalizador(localizacaoProduto.getText().trim());
        produto.setMarca(marca.getText().trim());
        produto.setUnidade(unidade.getText().trim());
        produto.setQuantidadeEstoque(quantidadeEstoque);

        try {
            ProdutosController.Cadastrarpecas(produto);
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
            limparDados();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar o cadastro do produto!");
        }
        limparDados();
    }//GEN-LAST:event_salvarActionPerformed

    private void descricaoPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoPecasActionPerformed

    private void valorRevendaPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorRevendaPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorRevendaPecasActionPerformed

    private void valorCompraPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCompraPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCompraPecasActionPerformed

    private void valorCompraPecasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorCompraPecasKeyReleased
        if ((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46)) {
            if (evt.getKeyCode() < 96 || evt.getKeyCode() > 105) {
                if (valorCompraPecas.getText().length() > 0) {
                    valorCompraPecas.setText(valorCompraPecas.getText().
                            substring(0, valorCompraPecas.getText().length() - 1));
                }
            }
        }
        if (evt.getKeyCode() == 44 || evt.getKeyCode() == 110) {
            valorCompraPecas.setText(valorCompraPecas.getText() + ".");
        }

    }//GEN-LAST:event_valorCompraPecasKeyReleased

    private void valorVarejoPecasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorVarejoPecasKeyReleased
        if ((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46)) {
            if (evt.getKeyCode() < 96 || evt.getKeyCode() > 105) {
                if (valorVarejoPecas.getText().length() > 0) {
                    valorVarejoPecas.setText(valorVarejoPecas.getText().
                            substring(0, valorVarejoPecas.getText().length() - 1));
                }
            }
        }
        if (evt.getKeyCode() == 44 || evt.getKeyCode() == 110) {
            valorVarejoPecas.setText(valorVarejoPecas.getText() + ".");
        }
    }//GEN-LAST:event_valorVarejoPecasKeyReleased

    private void valorRevendaPecasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorRevendaPecasKeyReleased
        if ((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46)) {
            if (evt.getKeyCode() < 96 || evt.getKeyCode() > 105) {
                if (valorRevendaPecas.getText().length() > 0) {
                    valorRevendaPecas.setText(valorRevendaPecas.getText().
                            substring(0, valorRevendaPecas.getText().length() - 1));
                }
            }
        }
        if (evt.getKeyCode() == 44 || evt.getKeyCode() == 110) {
            valorRevendaPecas.setText(valorRevendaPecas.getText() + ".");
        }
    }//GEN-LAST:event_valorRevendaPecasKeyReleased

    private void nomeProdutoPecasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeProdutoPecasKeyReleased
        nomeProdutoPecas.setText(nomeProdutoPecas.getText().toUpperCase());
    }//GEN-LAST:event_nomeProdutoPecasKeyReleased

    private void marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaKeyReleased
        marca.setText(marca.getText().toUpperCase());
    }//GEN-LAST:event_marcaKeyReleased

    private void localizacaoProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localizacaoProdutoKeyReleased
        localizacaoProduto.setText(localizacaoProduto.getText().toUpperCase());
    }//GEN-LAST:event_localizacaoProdutoKeyReleased

    private void unidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadeKeyReleased
        unidade.setText(unidade.getText().toUpperCase());
    }//GEN-LAST:event_unidadeKeyReleased

    private void qtdEstoqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtdEstoqueKeyReleased
        if ((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46)) {
            if (evt.getKeyCode() < 96 || evt.getKeyCode() > 105) {
                if (qtdEstoque.getText().length() > 0) {
                    qtdEstoque.setText(qtdEstoque.getText().
                            substring(0, qtdEstoque.getText().length() - 1));
                }
            }
        }
        if (evt.getKeyCode() == 44 || evt.getKeyCode() == 110) {
            qtdEstoque.setText(qtdEstoque.getText() + ".");
        }
    }//GEN-LAST:event_qtdEstoqueKeyReleased

    private void valorCompraPecasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorCompraPecasFocusLost
        if (botaoRevenda.isSelected()) {
            double cem = 100;
            BigDecimal cemBD = new BigDecimal(cem);
            BigDecimal margemLucro = new BigDecimal(margemLucroRevenda.getText().trim());
            BigDecimal valorCompra = new BigDecimal(valorCompraPecas.getText().trim());
            BigDecimal valorDaPorcentagemInformada = (valorCompra.multiply(margemLucro)).divide(cemBD);
            BigDecimal valorRevendaComAMargemInformada = valorCompra.add(valorDaPorcentagemInformada);
            valorRevendaPecas.setText(String.valueOf(valorRevendaComAMargemInformada));
        }
        if (botaoVarejo.isSelected()) {
            double cem = 100;
            BigDecimal cemBD = new BigDecimal(cem);
            BigDecimal margemLucro = new BigDecimal(margemLucroVarejo.getText().trim());
            BigDecimal valorCompra = new BigDecimal(valorCompraPecas.getText().trim());
            BigDecimal valorDaPorcentagemInformada = (valorCompra.multiply(margemLucro)).divide(cemBD);
            BigDecimal valorRevendaComAMargemInformada = valorCompra.add(valorDaPorcentagemInformada);
            valorVarejoPecas.setText(String.valueOf(valorRevendaComAMargemInformada));
        }


    }//GEN-LAST:event_valorCompraPecasFocusLost

    private void botaoRevendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRevendaActionPerformed
        if (botaoRevenda.isSelected()) {
            margemLucroRevenda.setEnabled(true);
        } else {
            margemLucroRevenda.setEnabled(false);
        }
    }//GEN-LAST:event_botaoRevendaActionPerformed

    private void botaoVarejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVarejoActionPerformed
        if (botaoVarejo.isSelected()) {
            margemLucroVarejo.setEnabled(true);
        } else {
            margemLucroVarejo.setEnabled(false);
        }
    }//GEN-LAST:event_botaoVarejoActionPerformed

    private void valorCompraPecasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorCompraPecasKeyTyped

    }//GEN-LAST:event_valorCompraPecasKeyTyped

    private void margemLucroRevendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_margemLucroRevendaKeyReleased
        if ((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46)) {
            if (evt.getKeyCode() < 96 || evt.getKeyCode() > 105) {
                if (margemLucroRevenda.getText().length() > 0) {
                    margemLucroRevenda.setText(margemLucroRevenda.getText().
                            substring(0, margemLucroRevenda.getText().length() - 1));
                }
            }
        }
        if (evt.getKeyCode() == 44 || evt.getKeyCode() == 110) {
            margemLucroRevenda.setText(margemLucroRevenda.getText() + ".");
        }

    }//GEN-LAST:event_margemLucroRevendaKeyReleased

    private void margemLucroVarejoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_margemLucroVarejoKeyReleased
        if ((evt.getKeyCode() < 48 || evt.getKeyCode() > 58) && (evt.getKeyCode() != 8 && evt.getKeyCode() != 46)) {
            if (evt.getKeyCode() < 96 || evt.getKeyCode() > 105) {
                if (margemLucroVarejo.getText().length() > 0) {
                    margemLucroVarejo.setText(margemLucroVarejo.getText().
                            substring(0, margemLucroVarejo.getText().length() - 1));
                }
            }
        }
        if (evt.getKeyCode() == 44 || evt.getKeyCode() == 110) {
            margemLucroVarejo.setText(margemLucroVarejo.getText() + ".");
        }

    }//GEN-LAST:event_margemLucroVarejoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoRevenda;
    private javax.swing.JRadioButton botaoVarejo;
    private javax.swing.JComboBox descricaoPecas;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField localizacaoProduto;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField margemLucroRevenda;
    private javax.swing.JTextField margemLucroVarejo;
    private javax.swing.JTextField nomeProdutoPecas;
    private javax.swing.JPanel painelEstipulador;
    private javax.swing.JTextField qtdEstoque;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField unidade;
    private javax.swing.JTextField valorCompraPecas;
    private javax.swing.JTextField valorRevendaPecas;
    private javax.swing.JTextField valorVarejoPecas;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {
            List<TipoProduto> produtos = ProdutosController.listarDescricao();
            for (TipoProduto produto : produtos) {

                descricaoPecas.addItem(produto);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel mostrar os produtos!");

        }
    }

    private void limparDados() {
        localizacaoProduto.setText("");
        nomeProdutoPecas.setText("");
        valorCompraPecas.setText("");
        valorRevendaPecas.setText("");
        valorVarejoPecas.setText("");
    }

}
