/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.apresentacao;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tcc.dao.ProdutosDao;
import tcc.dominio.Produtos;
import tcc.negocio.ProdutosController;
import util.Utilidades;

/**
 *
 * @author Breno-
 */
public class TabeladeMoto extends javax.swing.JInternalFrame {
        
    ProdutosController ProdutosController = new ProdutosController();

    
        static String[] colunas = {"Id", "NomeProduto", "Marca", "Und.", "Localizacao", "Estoque", "Preço de Atacado", "Preço de Varejo"};
        
    public TabeladeMoto() {
        initComponents();
        listarProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscaProduto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        vCompra = new javax.swing.JLabel();
        vRevenda = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        vVarejo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        localização = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        qtdEstoque = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        unidade = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaProdutosMoto = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lorem Auctor - Tabela de Produtos   ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buscaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscaProdutoKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/a2.png"))); // NOI18N
        jLabel17.setText("Pesquisar");

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setText("Pesquisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 255)));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel10.setText("Valor de Compra:");

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel18.setText("Valor de Revenda:");

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel19.setText("Valor de Varejo:");

        jLabel20.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel20.setText("$");

        vCompra.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        vCompra.setText("0.00");

        vRevenda.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        vRevenda.setText("0.00");

        jLabel21.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel21.setText("$");

        vVarejo.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        vVarejo.setText("0.00");

        jLabel22.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel22.setText("$");

        jLabel23.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel23.setText("Marca:");

        marca.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        marca.setText("-");

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel9.setText("Localização:");

        localização.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        localização.setText("-");

        jLabel24.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel24.setText("Quantidade no Estoque:");

        qtdEstoque.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        qtdEstoque.setText("-");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel11.setText("Descrição:");

        descricao.setBackground(new java.awt.Color(255, 0, 0));
        descricao.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 0, 0));
        descricao.setText("-");

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel12.setText("Identificador:");

        id.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        id.setText("-");

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1.png"))); // NOI18N
        jButton7.setText("Atualizar Produto");
        jButton7.setToolTipText("Atualizar Produto");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel13.setText("Unidade:");

        unidade.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        unidade.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vCompra))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vRevenda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vVarejo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(localização))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(marca))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(descricao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(qtdEstoque))
                                        .addGap(49, 49, 49))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(104, 104, 104)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(id)
                                    .addComponent(jLabel12)
                                    .addComponent(unidade))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(vCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vRevenda)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(vVarejo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localização)
                    .addComponent(unidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdEstoque)
                    .addComponent(id))
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1.png"))); // NOI18N
        jButton4.setText("Atualizar Tabela");
        jButton4.setToolTipText("Atualizar Informações da Tabela");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TabelaProdutosMoto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TabelaProdutosMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaProdutosMoto.setRowHeight(35);
        TabelaProdutosMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProdutosMotoMouseClicked(evt);
            }
        });
        TabelaProdutosMoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaProdutosMotoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaProdutosMotoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaProdutosMoto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaProdutoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscaProduto.setText(buscaProduto.getText().toUpperCase().trim());
            Utilidades.buscarProdutosMoto(buscaProduto.getText().toUpperCase().trim(), colunas, TabelaProdutosMoto);
        }
    }//GEN-LAST:event_buscaProdutoKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            buscaProduto.setText(buscaProduto.getText().toUpperCase());
            Utilidades.buscarProdutosMoto(buscaProduto.getText().toUpperCase().trim(), colunas, TabelaProdutosMoto);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(TabelaProdutosMoto.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Cliente.");
            return;
        }

        AtualizarPecasMoto apm = new AtualizarPecasMoto();
        TelaPrincipal.Addtelaprincipal(apm);
        TelaPrincipal.centralizar(apm);
        int i = TabelaProdutosMoto.getSelectedRow();
        AtualizarPecasMoto.produto(TabelaProdutosMoto.getValueAt(i, 1).toString(), TabelaProdutosMoto);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        listarProdutos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TabelaProdutosMotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaProdutosMotoKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        Utilidades.botaoEnterParaAdicionarProduto2(TabelaProdutosMoto, this, new BigDecimal (vCompra.getText()), new BigDecimal (vVarejo.getText()));
        }
    }//GEN-LAST:event_TabelaProdutosMotoKeyPressed

    private void TabelaProdutosMotoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaProdutosMotoKeyReleased
        Utilidades.informacoesProdutos(TabelaProdutosMoto, descricao, vCompra, vRevenda, vVarejo, marca, localização, qtdEstoque, unidade, id);
    }//GEN-LAST:event_TabelaProdutosMotoKeyReleased

    private void TabelaProdutosMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProdutosMotoMouseClicked
        Utilidades.informacoesProdutos(TabelaProdutosMoto, descricao, vCompra, vRevenda, vVarejo, marca, localização, qtdEstoque, unidade, id);
        if(evt.getClickCount() == 2){
        Utilidades.botaoEnterParaAdicionarProduto2(TabelaProdutosMoto, this, new BigDecimal (vCompra.getText()), new BigDecimal (vVarejo.getText()));
        }
    }//GEN-LAST:event_TabelaProdutosMotoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable TabelaProdutosMoto;
    public static javax.swing.JTextField buscaProduto;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel localização;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel qtdEstoque;
    private javax.swing.JLabel unidade;
    private javax.swing.JLabel vCompra;
    private javax.swing.JLabel vRevenda;
    private javax.swing.JLabel vVarejo;
    // End of variables declaration//GEN-END:variables
        
        public static void pesquisarProduto(String produto){
            buscaProduto.setText(produto);
            Utilidades.buscarProdutosMoto(produto, colunas, TabelaProdutosMoto);
        }
         private void listarProdutos() {
        try {
            List<Produtos> listaProdutos = ProdutosController.listarProdutosmoto();
            DefaultTableModel model = new DefaultTableModel(colunas, 0);
            for (Produtos y : listaProdutos) {
                model.addRow(new Object[] {
                     y.getIdProduto(),
                    y.getNomeProduto(),
                    y.getMarca(),
                    y.getUnidade(),
                    y.getLocalizador(),
                    y.getQuantidadeEstoque(),
                    y.getPrecoRevenda(),
                    y.getPrecoVarejo()
                });
            }
           TabelaProdutosMoto.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao listar os Produtos!");
        }
        Utilidades.larguraColunasTabelas(TabelaProdutosMoto);
    }
}